# Generated by Django 5.2.17 on 2026-10-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0002_connect_plan_to_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowancerelease',
            name='failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='allowancerelease',
            name='provider',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='allowancerelease',
            name='provider_reference',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='allowancerelease',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='allowancerelease',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('PROCESSING', 'Processing'), ('RELEASED', 'Released'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20),
        ),
    ]
