# Generated by Django 5.2.17 on 2026-10-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spend', '0003_allowancerelease_failure_reason_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
