# Generated by Django 5.2.17 on 2026-10-06 00:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deposits', '0001_initial'),
        ('investments', '0001_initial'),
        ('savings', '0001_initial'),
        ('spend', '0003_allowancerelease_failure_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('provider_id', models.CharField(max_length=100)),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('payment_method', models.CharField(default='mobilemoneyrw', max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('flutterwave_transaction_id', models.BigIntegerField(blank=True, null=True)),
                ('flutterwave_reference', models.CharField(blank=True, max_length=255)),
                ('authorization_url', models.URLField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deposit', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='deposits.deposit')),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('MOBILE_MONEY', 'Mobile Money'), ('BANK', 'Bank Account')], max_length=20)),
                ('beneficiary_name', models.CharField(max_length=255)),
                ('network', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('bank_code', models.CharField(blank=True, max_length=50)),
                ('branch_code', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_destinations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('ALLOWANCE', 'Allowance'), ('SAVINGS_WITHDRAWAL', 'Savings Withdrawal'), ('INVESTMENT_WITHDRAWAL', 'Investment Withdrawal')], max_length=30)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('PROCESSING', 'Processing'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=14, validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(default='RWF', max_length=3)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('flutterwave_transfer_id', models.BigIntegerField(blank=True, null=True)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('provider_status', models.CharField(blank=True, max_length=50)),
                ('fee', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowance_release', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='spend.allowancerelease')),
                ('investment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_payouts', to='investments.investmentaccount')),
                ('savings_bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_payouts', to='savings.savingsbucket')),
                ('savings_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='savings.savingstransaction')),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payments.payoutdestination')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
