# Generated by Django 5.2.17 on 2026-10-06 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
    ]
